spring:
  cloud:
    gateway:
      routes:
        - id: PRODUCTSERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/product/**,/schedule/**
        - id: USERSERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: MESSAGESERVICE
          uri: http://localhost:8090
          predicates:
            - Path=/notification/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
